List<String> grainsCereals = [
  "Rajgira",
  "Pearl millet",
  "Barley",
  "Besan",
  "Jowar",
  "Sookha Makka",
  "Makka",
  "Sweet corn",
  "Pasta",
  "Wheat pasta",
  "Quinoa",
  "Ragi",
  "Poha",
  "Vermicelli",
  "Bhel",
  "Brown rice",
  "Parboiled rice",
  "Rice",
  "Little millet",
  "Kodo millet",
  "Refined wheat flour",
  "Wheat flour",
  "Wheat",
  "Bulgur",
  "Wheat rava",
  "Wheat vermicelli",
  "Roasted vermicelli",
  "Idli Rava",
  "Rolled oats",
  "Rice flour",
  "Idli Rice"
];
List<String> beansLegumes = [
  "Chana dal",
  "Chana",
  "Urad dal split",
  "Urad gota",
  "Brown Cowpea",
  "White Cowpea",
  "Black beans",
  "Brown beans",
  "White beans",
  "Moong dal",
  "Whole Moong",
  "Horse gram",
  "Toor dal",
  "Brown toor",
  "Yellow toor",
  "Moth bean",
  "Dry peas",
  "Black rajma",
  "Brown rajma",
  "Red Rajma",
  "Masoor dal",
  "Whole masoor",
  "Brown soy bean",
  "White soy bean"
];
List<String> meat = [
  "Chicken leg skinless",
  "Chicken thigh skinless",
  "Chicken breast skinless",
  "Chicken wing skinless",
  "Chicken liver",
  "Chicken gizzard",
  "Country Chicken leg",
  "Country Chicken thigh",
  "Country Chicken breast",
  "Country Chicken wing",
  "Duck meat",
  "Turkey leg",
  "Turkey thigh",
  "Turkey breast",
  "Goat shoulder",
  "Goat chops",
  "Goat legs",
  "Goat liver",
  "Sheep shoulder",
  "Sheep chops",
  "Sheep leg",
  "Sheep liver",
  "Beef shoulder",
  "Beef chops",
  "Beef liver",
  "Pork shoulder",
  "Pork chops",
  "Pork ham",
  "Rabbit, chops",
  "Rabbit, leg",
  "Anchovy",
  "Bombay duck",
  "Hilsa",
  "Milk fish",
  "White Pomfret",
  "Red snapper",
  "Salmon",
  "Sardine",
  "Shark",
  "Tilapia",
  "Tuna",
  "Vanjaram",
  "Sea crab",
  "Lobster",
  "Mud crab",
  "Oyster",
  "Tiger Prawns",
  "Clam",
  "Octopus",
  "Squid",
  "Cat fish",
  "Catla",
  "Freshwater Eel",
  "Pangas",
  "Rohu",
  "Crab",
  "Big prawns",
  "Small prawns",
  "Tiger prawns"
];

List<String> eggs = [
  "Egg",
  "Egg white",
  "Egg yolk",
  "Boiled egg",
  "Boiled egg white",
  "Boiled egg yolk",
  "Duck egg",
  "Quail egg",
];

List<String> milkDairy = [
  "Butter",
  "Cheese",
  "Buffalo milk",
  "Cow milk",
  "Paneer",
  "Khoa",
  "Yoghurt",
];
List<String> leafyGreens = [
  "Green Amaranth leaves",
  "Red Amaranth leaves",
  "Spiny Amaranth",
  "Malabar spinach",
  "Tulsi",
  "Beet greens",
  "Paan leaves",
  "Brussels sprouts",
  "Chinese cabbage",
  "Collard greens",
  "Green cabbage",
  "Violet cabbage",
  "Cauliflower leaves",
  "Colocasia leaves",
  "Drumstick leaves",
  "Methi leaves",
  "Gongura leaves",
  "Red gongura",
  "Lettuce",
  "Mustard leaves",
  "Parsley",
  "Ponnaganni",
  "Radish leaves",
  "Spinach",
  "Tamarind leaves",
];

List<String> rootsTubers = [
  "Beet root",
  "Carrot",
  "Colocasia",
  "Big potato",
  "Small Potato",
  "Radish",
  "Brown sweet potato",
  "Pink Sweet potato",
  "Water Chestnut",
  "Elephant Yam",
  "Yam",
  "Big Onion",
  "Small Onion"
];
List<String> otherVeg = [
  "Ash gourd",
  "Bitter gourd",
  "Bottle gourd",
  "Round Bottle gourd",
  "Brinjal",
  "Broad beans",
  "Capsicum",
  "Red capsicum",
  "Yellow Capsicum",
  "Cauliflower",
  "Celery stalk",
  "Chow chow",
  "Cluster beans",
  "Baby corn",
  "Cucumber",
  "Orange cucumber",
  "Drumstick",
  "Field beans",
  "French beans",
  "Raw Jack fruit",
  "Jack fruit seeds",
  "Knol Khol",
  "Tindora",
  "Ladies finger",
  "Raw Mango",
  "Spring onions",
  "Raw Papaya",
  "Fresh Peas",
  "Plantain flower",
  "Green Plantain",
  "Pumpkin",
  "Ridge gourd",
  "Snake gourd",
  "Hybrid tomato",
  "Local tomato",
  "Green Zucchini",
  "Yellow Zucchini",
  "Chillies",
  "Button mushrooms",
  "Shiitake mushrooms",
  "Dried oyster mushrooms",
];
List<String> fruits = [
  "Apple",
  "Green Apple",
  "Small Apple",
  "Kashmir Apple",
  "Dried Apricot",
  "Processed Apricot",
  "Avocado",
  "Banana",
  "Red Banana",
  "Kala Jamun",
  "Red Cherries",
  "Black Currant",
  "Custard apple",
  "Dried dates",
  "Processed dates",
  "Fig",
  "Gooseberry",
  "Seeded black grapes",
  "Seeded red grapes",
  "Seedless green grapes",
  "Seedless black grapes",
  "Guava",
  "Pink Guava",
  "Jack fruit",
  "Water apple",
  "Karonda",
  "Kiwi",
  "Lemon juice",
  "Mosambi",
  "Litchi",
  "Banganapalli   Mango",
  "Neelam  Mango",
  "Totapari    Mango",
  "Mangosteen",
  "Manila Tamarind",
  "Musk melon",
  "Orange",
  "Palm fruit",
  "Papaya",
  "Peach",
  "Pear",
  "Pineapple",
  "Alubokhara",
  "Pomegranate",
  "Black Raisins",
  "Golden Raisins",
  "Rambutan",
  "Sapota",
  "Star fruit",
  "Strawberry",
  "Tamarind pulp",
  "Dark green Water melon",
  "Pale green Water melon",
  "Jujube",
];


List<String> nutsSeeds = [
  "Cashew nut",
  "Chia seeds",
  "Dry Coconut",
  "Fresh Coconut",
  "Haleem seeds",
  "Black Gingelly seeds",
  "White Gingelly seeds",
  "Ground nut",
  "Mustard seeds",
  "Flax seeds",
  "Niger seeds",
  "Pine nuts",
  "Pistachio nuts",
  "Safflower seeds",
  "Sunflower seeds",
  "Walnut",
  "Watermelon seeds",
  "Peanut Powder",
];

List<String> oilFats = [
  "Com oil",
  "Cotton seed oil",
  "Gingelly oil",
  "Groundnut oil",
  "Mustard oil",
  "Olive oil",
  "Palm  oil",
  "Rice bran oil",
  "Safflower oil",
  "Safflower oil",
  "Soyabean oil",
  "Sunflower oil",
  "Ghee",
  "Vanaspati",
  "Coconut milk",
];

List<String> herbs = [
  "Coriander leaves",
  "Curry leaves",
  "Big Garlic",
  "Small Garlic",
  "Ginger",
  "Mango ginger",
  "Mint leaves",
];

List<String> condiments = [
  "Green Cardamom",
  "Black Cardamom",
  "Red Chillies",
  "Cloves",
  "Coriander seeds",
  "Cumin seeds",
  "Fenugreek seeds",
  "Mace",
  "Nutmeg",
  "Omum",
  "Pippali",
  "Black Pepper",
  "Poppy seeds",
  "Turmeric powder",
  "Table Salt",
];
